version: '3'
services: 
    cypress_test:
        image: e2e-cypress
        build: 
            context: .
            dockerfile: ./Dockerfile
            target: report
        ports:
          - 3000:3000
        volumes: 
            - ./dockerReports/:/app/cypress/reports